// Regenerate the typed API client (lib/api/schema.ts) from the backend OpenAPI
// spec. Uses openapi-typescript's programmatic API so the command is
// shell-agnostic (works on bash, zsh, cmd, PowerShell, and CI).
//
// Override the source with OPENAPI_URL, e.g. a local backend:
//   OPENAPI_URL=http://localhost:3000/api/openapi.json npm run gen:api
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const SPEC_URL =
  process.env.OPENAPI_URL ?? "https://iwantmymtg.net/api/openapi.json";
const OUTPUT = fileURLToPath(new URL("../lib/api/schema.ts", import.meta.url));

const BANNER =
  "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n\n";

const ast = await openapiTS(new URL(SPEC_URL));
await writeFile(OUTPUT, BANNER + astToString(ast));
console.log(`Generated ${OUTPUT} from ${SPEC_URL}`);
